- name: Set release facts
  ansible.builtin.set_fact:
    throne_download_url: "https://github.com/throneproj/Throne/releases/download/{{ throne_version }}/Throne-{{ throne_version }}-debian-x64.deb"

- name: Download Throne release
  ansible.builtin.get_url:
    url: "{{ throne_download_url }}"
    dest: "/tmp/throne-{{ throne_version }}.deb"
  become: true

- name: Install Throne from .deb
  ansible.builtin.apt:
    auto_install_module_deps: true
    install_recommends: true
    deb: "/tmp/throne-{{ throne_version }}.deb"
  become: true
