---
- name: Create user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    groups: sudo
    state: present
- name: Sudoer
  community.general.sudoers:
    name: "{{ username }}"
    user: "{{ username }}"
    commands:
      - ALL
    nopassword: true
