---
- name: Install prerequisites
  apt:
    name: 
      - apt-transport-https
      - curl
      - gnupg
    state: present

- name: Import Microsoft GPG key
  shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -D -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/packages.microsoft.gpg

- name: Add VS Code repository
  shell: echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | tee /etc/apt/sources.list.d/vscode.list

- name: Install VS Code
  apt:
    name: code
    state: present
    update_cache: yes
