---
- name: Install prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
    state: present

- name: Import xpipe GPG key
  become: true
  ansible.builtin.shell: |
    curl -sL https://xpipe.io/signatures/crschnick.asc | gpg --dearmor | sudo tee /usr/share/keyrings/xpipe.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/xpipe.gpg

- name: Add xpipe repository
  become: true
  ansible.builtin.aptre:
    repo: deb [signed-by=/usr/share/keyrings/xpipe.gpg] https://apt.xpipe.io stable main
    state: present

- name: Install xpipe
  become: true
  ansible.builtin.apt:
    name: xpipe
    state: present
    update_cache: yes
