- name: Download chrome file
  ansible.builtin.get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: /tmp/chrome.deb

- name: Install Google Chrome
  become: true
  ansible.builtin.apt:
    auto_install_module_deps: true
    install_recommends: true
    deb: /tmp/chrome.deb
